### ISSUE TITLE
Expand external IdP support

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-signin-widget#571]
### I'm submitting a
  - feature request

### Background info

Currently, the Widget supports adding social IdPs to `config.idps` but checks each entry's `type` against a hardcoded whitelist (`GOOGLE`, `FACEBOOK`, etc). The `type` property is simply used to set the button's CSS class, and doesn't infer any functional differences.

We need to expand this support to allow arbitrary IdPs to be added. They could be a well-known type like Google or Facebook, or a generic SAML or OIDC IdP.

https://oktawiki.atlassian.net/wiki/spaces/~nate.barbettini/pages/584977730/Improved+IdP+support+in+Auth.js+and+the+Sign-in+Widget

### Tasks

- [ ] Remove the whitelist of IdP types
- [ ] Add a `buttonClass` property and soft-deprecate `type`
- [ ] Add a `label` property
- [ ] Work with Nate/design to create a "generic" IdP look

**Comment by nbarbettini** [comment]
Closed via https://github.com/okta/okta-signin-widget/pull/628
